language: node_js
node_js:
  - "lts/*"
cache:
  npm: true
services:
  - xvfb
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
script:
  - npm run lint
  - npm run build:all
  - npm run test:ci
